export const popularSkills = [
  'Cooking',
  'Cleaning',
  'Shopping',
  'Menu Planning',
  'Meal Preparation',
  'Money Management and budgeting',
  'Use of Public Transportation',
  'Personal Health and Hygiene',
  'Self-Advocacy',
  'Independent Recreation and Participation',
  'Use of Medical and Dental Services',
  'Community Resource Awareness',
  'Home and Community Safety',
]

export const dummySkills = [
  'Home and Community Safety',
  'Use of medical services',
  'Cooking',
  'Menu Planning',
  'Meal Prep',
  'Cleaning',
  'Shopping in natural environment',
  'Self-advocacy training',
  'Personal hygiene',
  'Money Management',
  'Use of public transportation',
  'Transportation',
  'Communication',
  'Social Skills',
]
